# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Python app to Azure Web App - py-flask-test

on:
  push:
    branches:
      - Feature_Experimental_QuestionMatching

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Install Python dependencies
      run: |
        python3 -m venv env
        source env/bin/activate
        pip install -r requirements.txt
    - name: Zip the application files
      run: zip -r myapp.zip .

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'py-flask-test'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2ce18b5c4ad64708af20c32c985c006d }}
        package: './myapp.zip'